backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Imagem Grande", name: "full_image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "portfolio"
    label: "Portfolio"
    folder: "src/pages/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "portfolio-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Position", name: "position", widget: "number", valueType: "int"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Images", name: images, widget: list, fields: [{label: Image, name: src, widget: image}, {label: alt, name: alt, widget: string}, {label: width, name: width, widget: "number", valueType: "int"}, {label: height, name: height, widget: "number", valueType: "int"}]}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/quem-somos/index.md"
        label: "Sobre"
        name: "Sobre"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "sobre-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/clientes/index.md"
        label: "Clientes"
        name: "Clientes"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "clients-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/index.md"
        label: "Home page"
        name: "index"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Welcome Title", name: welcomeTitle, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: Banners, name: banners, widget: list, fields: [{label: Image, name: src, widget: image}, {label: alt, name: alt, widget: string}, {label: link, name: link, widget: string}]}
          - {label: Testimonials, name: wrapperTestimonials, widget: object, fields: [{ label: Title, name: title, widget: string},{label: Testimonials, name: testimonials, widget: list, fields: [{label: Author, name: author, widget: string}, {label: name, name: name, widget: string}, {label: quote, name: quote, widget: string}, {label: avatar, name: avatar, widget: image}]}]}
          - {label: Portfolio, name: miniPortfolio, widget: object, fields: [{ label: Title, name: title, widget: string},{label: Imagens, name: images, widget: list, fields: [{label: Alt, name: alt, widget: string}, {label: src, name: src, widget: image}, {label: title, name: title, widget: string},{label: url, name: url, widget: string}]}]}
